### PR TITLE
Add solidityX to language page

### PR DESCRIPTION
**Pull request by Juuddi**
- Add SolidityX to languages page
- Add overview + explainer to languages page
- Fix typo noted [here](https://github.com/dominant-strategies/quai-docs/pull/51#issuecomment-1812217057) by @saiaman
- Fix headings on languages page

### CODE REVIEW

**Comment by Juuddi** [comment]
Closes #53

**Review by maxbibeau — CHANGES_REQUESTED** [review]
Typo: 
"Quai Network runs a modified Ethereum Virtual Machine environment that provides internal *and* cross-chain smart contract execution across zone chain in the network."

Should be "across zone chain**s**"

**Comment by Juuddi** [comment]
> Typo: "Quai Network runs a modified Ethereum Virtual Machine environment that provides internal _and_ cross-chain smart contract execution across zone chain in the network."
> 
> Should be "across zone chain**s**"

Resolved with https://github.com/dominant-strategies/quai-docs/pull/53/commits/f63b2d45b22099cf9ec06d71a2e16004ba203046

**Review by maxbibeau — APPROVED** [review]
LGTM

**Pull request merged**
